import SearchBar from "./components/SearchBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-500 h-screen w-screen flex flex-col justify-start`}
      >
        <div className={`border-2 h-1/4 flex flex-col justify-center items-center`}>
          <SearchBar />
        </div>
        {children}
      </body>
    </html>
  );
}
